version: 2

jobs: 
  build:
    machine: true

    steps: 
      - checkout
      - run:
          name: Build API
          command: |
            docker-compose -f ../docker-compose.yml run app python manage.py test tests
